// ============================================
// SumiWire PRO - Actions
// ============================================

export const ACTIONS = {
  // Pages
  ADD_PAGE: 'ADD_PAGE',
  DELETE_PAGE: 'DELETE_PAGE',
  DUPLICATE_PAGE: 'DUPLICATE_PAGE',
  SET_ACTIVE_PAGE: 'SET_ACTIVE_PAGE',
  SET_PAGE_FORMAT: 'SET_PAGE_FORMAT',
  REORDER_PAGES: 'REORDER_PAGES',
  SET_PAGE_POSITION: 'SET_PAGE_POSITION',

  // Panels
  ADD_PANEL: 'ADD_PANEL',
  UPDATE_PANEL: 'UPDATE_PANEL',
  DELETE_PANELS: 'DELETE_PANELS',

  // Bubbles
  ADD_BUBBLE: 'ADD_BUBBLE',
  UPDATE_BUBBLE: 'UPDATE_BUBBLE',
  DELETE_BUBBLES: 'DELETE_BUBBLES',

  // Drawing
  ADD_STROKE: 'ADD_STROKE',
  DELETE_STROKE: 'DELETE_STROKE',
  CLEAR_DRAWINGS: 'CLEAR_DRAWINGS',

  // Selection
  SET_SELECTION: 'SET_SELECTION',
  ADD_TO_SELECTION: 'ADD_TO_SELECTION',
  CLEAR_SELECTION: 'CLEAR_SELECTION',
  SET_EDITING_IMAGE: 'SET_EDITING_IMAGE',

  // Tools
  SET_TOOL: 'SET_TOOL',
  SET_DRAWING_SETTINGS: 'SET_DRAWING_SETTINGS',

  // View
  SET_VIEW_MODE: 'SET_VIEW_MODE',
  SET_ZOOM: 'SET_ZOOM',
  SET_PAN: 'SET_PAN',
  TOGGLE_GRID: 'TOGGLE_GRID',
  TOGGLE_GUIDES: 'TOGGLE_GUIDES',
  TOGGLE_SNAP: 'TOGGLE_SNAP',

  // Layout
  APPLY_LAYOUT: 'APPLY_LAYOUT',
  TOGGLE_LAYOUT_LOCK: 'TOGGLE_LAYOUT_LOCK',

  // Theme
  TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',

  // History
  UNDO: 'UNDO',
  REDO: 'REDO',
  SAVE_HISTORY: 'SAVE_HISTORY',

  // UI
  TOGGLE_SETTINGS: 'TOGGLE_SETTINGS',
  TOGGLE_EXPORT: 'TOGGLE_EXPORT',
  TOGGLE_HELP: 'TOGGLE_HELP',

  // Project
  SET_PROJECT_NAME: 'SET_PROJECT_NAME',
  SET_PROJECT_ID: 'SET_PROJECT_ID',
  LOAD_PROJECT: 'LOAD_PROJECT',
  NEW_PROJECT: 'NEW_PROJECT',

  // Clipboard
  COPY: 'COPY',
  PASTE: 'PASTE',

  // Brushes
  ADD_BRUSH: 'ADD_BRUSH',
  DELETE_BRUSH: 'DELETE_BRUSH',
  SET_ACTIVE_BRUSH: 'SET_ACTIVE_BRUSH',

  // Canvas flip / rotation / view
  TOGGLE_FLIP_H: 'TOGGLE_FLIP_H',
  SET_CANVAS_ROTATION: 'SET_CANVAS_ROTATION',
  TOGGLE_READING_ORDER: 'TOGGLE_READING_ORDER',

  // Layers (Phase 2)
  ADD_LAYER: 'ADD_LAYER',
  DELETE_LAYER: 'DELETE_LAYER',
  RENAME_LAYER: 'RENAME_LAYER',
  DUPLICATE_LAYER: 'DUPLICATE_LAYER',
  REORDER_LAYERS: 'REORDER_LAYERS',
  SET_ACTIVE_LAYER: 'SET_ACTIVE_LAYER',
  TOGGLE_LAYER_VISIBILITY: 'TOGGLE_LAYER_VISIBILITY',
  TOGGLE_LAYER_LOCK: 'TOGGLE_LAYER_LOCK',
  SET_LAYER_OPACITY: 'SET_LAYER_OPACITY',
  SET_LAYER_BLEND_MODE: 'SET_LAYER_BLEND_MODE',
  TOGGLE_CLIPPING_MASK: 'TOGGLE_CLIPPING_MASK',
  CLEAR_LAYER_STROKES: 'CLEAR_LAYER_STROKES',
};